import React, { useState } from 'react';
import { ReportAnalysis, Finding } from '../types';
import { MEDICAL_GLOSSARY } from '../services/simplifierService';

interface ResultsViewProps {
  analysis: ReportAnalysis;
  onNewAnalysis: () => void;
  onOpenDoctorQuestions: () => void;
}

export const ResultsView: React.FC<ResultsViewProps> = ({
  analysis,
  onNewAnalysis,
  onOpenDoctorQuestions,
}) => {
  const [selectedFinding, setSelectedFinding] = useState<Finding | null>(null);
  const [copiedRaw, setCopiedRaw] = useState(false);
  const [copiedSummary, setCopiedSummary] = useState(false);

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadSummary = () => {
    const findingsText = analysis.keyFindings
      .map(
        (f) =>
          `• ${f.name} [${f.statusLabel}]: ${f.explanation} -> ${f.clinicalMeaning}`
      )
      .join('\n');

    const doctorQuestionsText = analysis.doctorQuestions
      .map((q, i) => `${i + 1}. ${q}`)
      .join('\n');

    const summaryContent = `==============================================
CLARIFYHEALTH - PATIENT MEDICAL REPORT SUMMARY
==============================================
Document: ${analysis.fileName}
Processed: ${analysis.dateProcessed}
Test Type: ${analysis.testType}

YOUR RESULTS AT A GLANCE:
${analysis.glanceSummary}

KEY FINDINGS:
${findingsText}

WHAT THIS MEANS FOR YOU:
${analysis.whatThisMeans}

QUESTIONS TO ASK YOUR DOCTOR:
${doctorQuestionsText}

----------------------------------------------
AI SIMPLIFICATION NOTE:
This summary was generated by AI to help you understand your results.
It is not a substitute for professional medical advice. Always consult
your physician for clinical guidance.
==============================================`;

    const blob = new Blob([summaryContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `ClarifyHealth_Summary_${analysis.fileName.replace(/\.[^/.]+$/, '')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCopyRaw = () => {
    navigator.clipboard.writeText(analysis.rawText);
    setCopiedRaw(true);
    setTimeout(() => setCopiedRaw(false), 2000);
  };

  const handleCopySummary = () => {
    const text = `${analysis.testType}\n\n${analysis.glanceSummary}\n\nKey Findings:\n${analysis.keyFindings
      .map((f) => `- ${f.name} (${f.statusLabel}): ${f.explanation}`)
      .join('\n')}\n\nWhat This Means:\n${analysis.whatThisMeans}`;
    navigator.clipboard.writeText(text);
    setCopiedSummary(true);
    setTimeout(() => setCopiedSummary(false), 2000);
  };

  // Helper to render status chip
  const renderStatusBadge = (status: string, label: string) => {
    switch (status) {
      case 'normal':
        return (
          <span className="bg-[#e6f4ea] text-[#1e8e3e] px-2.5 py-0.5 rounded-full text-xs font-semibold whitespace-nowrap inline-flex items-center gap-1">
            <span className="w-1.5 h-1.5 rounded-full bg-[#1e8e3e]" />
            {label || 'Normal'}
          </span>
        );
      case 'slightly_low':
      case 'low':
        return (
          <span className="bg-[#fce8e6] text-[#d93025] px-2.5 py-0.5 rounded-full text-xs font-semibold whitespace-nowrap inline-flex items-center gap-1">
            <span className="w-1.5 h-1.5 rounded-full bg-[#d93025]" />
            {label || 'Slightly Low'}
          </span>
        );
      case 'high':
      case 'slightly_high':
      case 'critical':
        return (
          <span className="bg-[#fce8e6] text-[#d93025] px-2.5 py-0.5 rounded-full text-xs font-semibold whitespace-nowrap inline-flex items-center gap-1">
            <span className="w-1.5 h-1.5 rounded-full bg-[#d93025]" />
            {label || 'Elevated'}
          </span>
        );
      default:
        return (
          <span className="bg-[#eff4ff] text-[#0059bb] px-2.5 py-0.5 rounded-full text-xs font-semibold whitespace-nowrap">
            {label || 'Info'}
          </span>
        );
    }
  };

  return (
    <div className="w-full max-w-[1200px] mx-auto px-4 md:px-6 pt-24 pb-16">
      {/* Header Area */}
      <div className="mb-8 flex flex-col md:flex-row justify-between items-start md:items-end gap-4 border-b border-[#c1c6d7] pb-6 relative overflow-hidden">
        <div className="relative z-10">
          <div className="flex items-center gap-2 mb-1.5">
            <span
              className="material-symbols-outlined text-[#006b24] text-xl"
              style={{ fontVariationSettings: "'FILL' 1" }}
            >
              check_circle
            </span>
            <span className="text-xs font-bold text-[#006b24] uppercase tracking-wider">
              Analysis Complete
            </span>
          </div>

          <h1 className="text-2xl md:text-3xl font-bold text-[#0b1c30] tracking-tight">
            {analysis.fileName}
          </h1>
          <p className="text-sm text-[#414754] mt-1">
            Processed successfully. Simplification ready.
          </p>
        </div>

        {/* Header Action Buttons */}
        <div className="flex flex-wrap gap-2.5 relative z-10 w-full md:w-auto no-print">
          <button
            onClick={handlePrint}
            className="flex-1 md:flex-none flex items-center justify-center gap-1.5 border border-[#0059bb] text-[#0059bb] px-4 py-2 rounded-lg text-sm font-semibold hover:bg-[#eff4ff] transition-colors cursor-pointer"
          >
            <span className="material-symbols-outlined text-base">print</span>
            <span>Print</span>
          </button>

          <button
            onClick={onNewAnalysis}
            className="flex-1 md:flex-none flex items-center justify-center gap-1.5 border border-[#0059bb] text-[#0059bb] px-4 py-2 rounded-lg text-sm font-semibold hover:bg-[#eff4ff] transition-colors cursor-pointer"
          >
            <span className="material-symbols-outlined text-base">restart_alt</span>
            <span>New Analysis</span>
          </button>

          <button
            onClick={handleDownloadSummary}
            className="flex-1 md:flex-none flex items-center justify-center gap-1.5 bg-[#007BFF] hover:bg-[#0059bb] text-white px-4 py-2 rounded-lg text-sm font-semibold transition-all shadow-xs cursor-pointer"
          >
            <span className="material-symbols-outlined text-base">download</span>
            <span>Download Summary</span>
          </button>
        </div>

        {/* Medical Accent Watermark */}
        <span
          className="material-symbols-outlined absolute -right-6 -top-6 text-[140px] text-[#dce9ff] opacity-40 z-0 pointer-events-none select-none hidden md:block"
          style={{ fontVariationSettings: "'FILL' 1" }}
        >
          prescriptions
        </span>
      </div>

      {/* Segmented 2-Column View */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Side: Simplified Summary (7 cols) */}
        <section className="lg:col-span-7 flex flex-col gap-6">
          <div className="bg-white border border-[#c1c6d7] rounded-xl p-6 md:p-8 shadow-[0_4px_24px_rgba(0,89,187,0.04)] relative overflow-hidden flex-grow">
            {/* Blue Left Stripe */}
            <div className="absolute left-0 top-0 bottom-0 w-1.5 bg-[#0059bb]" />

            {/* Section Header */}
            <div className="flex items-center justify-between gap-2 mb-6">
              <div className="flex items-center gap-2.5">
                <span className="material-symbols-outlined text-[#0059bb] bg-[#eff4ff] p-2 rounded-full text-xl">
                  summarize
                </span>
                <h2 className="text-xl md:text-2xl font-bold text-[#0b1c30]">
                  Simplified Summary
                </h2>
              </div>

              <button
                onClick={handleCopySummary}
                className="text-xs text-[#555f6b] hover:text-[#0059bb] inline-flex items-center gap-1 border border-[#c1c6d7] px-2.5 py-1 rounded-md bg-white hover:bg-[#F8FAFC] transition-colors cursor-pointer"
                title="Copy formatted summary"
              >
                <span className="material-symbols-outlined text-sm">
                  {copiedSummary ? 'check' : 'content_copy'}
                </span>
                <span>{copiedSummary ? 'Copied' : 'Copy'}</span>
              </button>
            </div>

            {/* Glance Section */}
            <div className="mb-6">
              <h3 className="text-lg font-bold text-[#0b1c30] mb-2 border-b border-[#e5eeff] pb-2">
                Your Results at a Glance
              </h3>
              <p className="text-base text-[#414754] leading-relaxed">
                {analysis.glanceSummary}
              </p>
            </div>

            {/* Key Findings Section */}
            <div className="mb-6">
              <h3 className="text-lg font-bold text-[#0b1c30] mb-3">
                Key Findings
              </h3>
              <div className="space-y-3">
                {analysis.keyFindings.map((finding) => (
                  <div
                    key={finding.id}
                    onClick={() =>
                      setSelectedFinding(
                        selectedFinding?.id === finding.id ? null : finding
                      )
                    }
                    className={`p-3.5 rounded-lg border transition-all cursor-pointer ${
                      selectedFinding?.id === finding.id
                        ? 'border-[#0059bb] bg-[#eff4ff]'
                        : 'border-[#e5eeff] bg-[#F8FAFC] hover:bg-[#eff4ff]/60'
                    }`}
                  >
                    <div className="flex flex-wrap items-center justify-between gap-2 mb-1.5">
                      <div className="flex items-center gap-2">
                        <strong className="text-sm md:text-base font-semibold text-[#0b1c30]">
                          {finding.name}:
                        </strong>
                        {renderStatusBadge(finding.status, finding.statusLabel)}
                      </div>

                      <span className="text-xs text-[#0059bb] font-medium flex items-center gap-0.5">
                        <span className="material-symbols-outlined text-sm">
                          {selectedFinding?.id === finding.id ? 'expand_less' : 'help_outline'}
                        </span>
                        <span>{selectedFinding?.id === finding.id ? 'Hide Details' : 'What is this?'}</span>
                      </span>
                    </div>

                    <p className="text-sm text-[#414754] leading-relaxed">
                      {finding.explanation}{' '}
                      <span className="text-[#0b1c30] font-medium">
                        {finding.clinicalMeaning}
                      </span>
                    </p>

                    {/* Interactive Explainer Drawer */}
                    {selectedFinding?.id === finding.id && (
                      <div className="mt-3 pt-3 border-t border-[#adc7ff] bg-white p-3 rounded-md shadow-xs">
                        <div className="flex items-center gap-1.5 text-xs font-bold text-[#0059bb] uppercase tracking-wider mb-1">
                          <span className="material-symbols-outlined text-sm">
                            medical_information
                          </span>
                          Clinical Context
                        </div>
                        <p className="text-xs text-[#414754] leading-relaxed">
                          {Object.entries(MEDICAL_GLOSSARY).find(([k]) =>
                            finding.name.toLowerCase().includes(k)
                          )?.[1]?.simpleDefinition ||
                            'This marker reflects biochemical homeostasis. Variations are interpreted by physicians within your full clinical profile.'}
                        </p>
                        {finding.value && (
                          <div className="mt-2 text-xs font-mono bg-[#F8FAFC] px-2 py-1 rounded border border-[#c1c6d7] text-[#0b1c30]">
                            Your Value: <strong>{finding.value}</strong> • Ref Range: {finding.referenceRange || 'Standard range'}
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>

            {/* What This Means For You */}
            <div className="mb-6">
              <h3 className="text-lg font-bold text-[#0b1c30] mb-2">
                What This Means For You
              </h3>
              <p className="text-sm md:text-base text-[#414754] leading-relaxed bg-[#F8FAFC] p-4 rounded-lg border border-[#e5eeff]">
                {analysis.whatThisMeans}
              </p>
            </div>

            {/* Doctor Questions CTA */}
            <div className="mb-6 flex flex-col sm:flex-row items-start sm:items-center justify-between p-4 bg-[#eff4ff] rounded-xl border border-[#adc7ff] gap-3">
              <div>
                <h4 className="text-sm font-bold text-[#004493]">
                  Prepare for your doctor appointment
                </h4>
                <p className="text-xs text-[#555f6b] mt-0.5">
                  We generated {analysis.doctorQuestions.length} tailored questions based on your results.
                </p>
              </div>
              <button
                onClick={onOpenDoctorQuestions}
                className="bg-[#0059bb] hover:bg-[#004493] text-white text-xs font-semibold px-3.5 py-2 rounded-lg transition-colors flex items-center gap-1 cursor-pointer shrink-0"
              >
                <span className="material-symbols-outlined text-sm">question_answer</span>
                <span>View Doctor Questions</span>
              </button>
            </div>

            {/* AI Simplification Note */}
            <div className="p-4 bg-[#eff4ff] rounded-lg border border-[#adc7ff]">
              <div className="flex items-start gap-3">
                <span className="material-symbols-outlined text-[#0059bb] text-xl mt-0.5">
                  info
                </span>
                <div>
                  <p className="text-sm font-semibold text-[#0b1c30] mb-0.5">
                    AI Simplification Note
                  </p>
                  <p className="text-xs md:text-sm text-[#414754] leading-relaxed">
                    This summary was generated by AI to help you understand your results. It is
                    not a substitute for professional medical advice. Always consult your doctor
                    for a full clinical interpretation.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Right Side: Original Data Extracted (5 cols) */}
        <section className="lg:col-span-5 flex flex-col gap-6">
          <div className="bg-[#F8FAFC] border border-[#c1c6d7] rounded-xl p-6 flex-grow flex flex-col shadow-xs">
            {/* Header */}
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <span className="material-symbols-outlined text-[#555f6b]">
                  data_object
                </span>
                <h2 className="text-base md:text-lg font-bold text-[#0b1c30]">
                  Original Data Extracted
                </h2>
              </div>
              <span className="text-xs font-medium text-[#414754] bg-white px-2.5 py-0.5 rounded-md border border-[#c1c6d7]">
                Raw Text Snippet
              </span>
            </div>

            <p className="text-xs text-[#555f6b] mb-3 leading-relaxed">
              The following text was successfully extracted from your uploaded file. This is the raw data used to generate the summary.
            </p>

            {/* Raw Extracted Container */}
            <div className="bg-white border border-[#c1c6d7] rounded-lg p-4 overflow-auto flex-grow h-[420px] font-mono text-xs text-[#414754] whitespace-pre leading-relaxed shadow-inner">
              {analysis.rawText}
            </div>

            {/* Quick Actions Footer for Raw Data */}
            <div className="mt-3 pt-3 border-t border-[#c1c6d7] flex items-center justify-between text-xs text-[#555f6b]">
              <span className="flex items-center gap-1">
                <span className="material-symbols-outlined text-sm text-[#006b24]">
                  check
                </span>
                Zero database retention active
              </span>

              <button
                onClick={handleCopyRaw}
                className="text-[#0059bb] hover:underline font-semibold flex items-center gap-1 cursor-pointer"
              >
                <span className="material-symbols-outlined text-sm">
                  {copiedRaw ? 'done' : 'content_copy'}
                </span>
                <span>{copiedRaw ? 'Copied' : 'Copy Raw Text'}</span>
              </button>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};
